### ISSUE TITLE
FAILED 2

### ISSUE THREAD

**Issue by divined** [weareinteractive/ansible-mongodb#4]
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service mongod: host"}

**Comment by divined** [comment]
```
- name: Create service
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  notify: restart mongodb
  with_items:
    - etc/systemd/system/mongod.service
```

./etc/systemd/system/mongod.service.j2:

```
[Unit]
Description=High-performance, schema-free document-oriented database
After=network.target

[Service]
User=mongodb
ExecStart=/usr/bin/mongod --quiet --config /etc/mongod.conf

[Install]
WantedBy=multi-user.target
```
